instagram:
  apple:
    - iphoneography
    - iphoneonly
    - iphonephotography
    - shotoniphone
  architecture:
    - archdaily
    - archidaily
    - archilovers
    - architecturelovers
    - architecturephotography
    - architectureporn
    - architexture
  astrophotography:
    - astrophoto
    - astrophotography
    - ig_astrophotography
    - ig_nightphotography
    - milkywaychasers
    - milkywaygalaxy
    - natgeospace
    - nightimages
    - nightscape
    - nightscaper
    - nightshooters
    - nightsky
    - rsa_night
    - skymasters
    - stargazing
    - starrynight
  birds:
    - birdextreme
    - birdfreaks
    - birding
    - birdlover
    - birdlovers
    - birdphotography
    - birdstagram
    - eye_spy_birds
    - igbirds
    - instabird
    - instabirds
    - nuts_about_birds
    - your_best_birds
  blackandwhite:
    - blackandwhitephoto
    - blackandwhitephotography
    - blancoynegro
    - bnw_captures
    - bnw_city
    - bnw_globe
    - bnw_life
    - bnw_magazine
    - bnw_planet
    - bnw_society
    - bnwmood
    - bw_lover
    - bw_photooftheday
    - monochrome
  caracas:
    - ccs
    - ig_caracas
  cars:
    - carinstagram
    - carporn
    - carsofinstagram
    - carstagram
    - igcars
    - instacars
  cats:
    - animalsofinstagram
    - cat_features
    - catlove
    - catlover
    - catlovers
    - catoftheday
    - cats_of_instagram
    - cats_of_world
    - catsagram
    - catsofig
    - catsofinstagram
    - catstagram
    - caturday
    - catvalentine
    - catwalk
    - cutecat
    - ilovemycat
    - instacat
    - instacats
    - instagramcats
    - katze
    - kitten
    - kittylove
    - lovecats
    - meow
  chattanooga:
    - nooga
    - noogagram
  cityscapes:
    - city_explore
    - citybestpics
    - citylife
    - citylimitless
    - cityphotography
    - cityscape
    - cityview
    - guardiancities
    - ic_thecity
    - ig_captures_city
    - seemycity
    - skyline
    - theprettycities
  ciudaddemexico:
    - cdmx
    - ciudaddemexico
    - df
    - igerscdmx
    - igersdf
    - mexicocity
    - mexicodf
  classiccars:
    - drivetastefully
    - retrocars
    - vintagecars
  coffee:
    - coffeetime
    - cafe
    - coffeelover
    - coffeeaddict
    - coffeegram
    - instacoffee
    - caffeine
    - coffeeshop
    - coffeelovers
    - coffeeholic
    - coffeebreak
    - coffeelove
    - coffeelife
  concerts:
    - bandphotographer
    - concertphoto
    - concertphotographer
    - concertphotography
    - concertphotos
    - liveconcertphotography
    - livemusic
    - livemusicphotographer
    - livemusicphotography
    - livephotography
    - musiclife
    - musicphoto
    - musicphotographer
    - musicphotography
    - rocknroll
    - rockphotography
  districtofcolumbia:
    - acreativedc
    - dcitystyle
    - districtofcolumbia
    - exploredc
    - exposeddc
    - fotodc
    - igdc
    - igersdc
    - mydccool
    - streetmeetdc
    - walkwithlocals
    - washingtondaily
    - washingtondc
  dogs:
    - barkbox
    - bestwoof
    - dog_features
    - doglife
    - doglover
    - doglovers
    - dogoftheday
    - dogs_of_instagram
    - dogscorner
    - dogslife
    - dogsofig
    - instagramdogs
    - instapet
    - lovepuppies
    - petsagram
    - petsofinstagram
    - petstagram
    - pup
    - puppies
    - puppiesofinstagram
    - puppylove
    - weeklyfluff
  film:
    - analogphotography
    - believeinfilm
    - filmisnotdead
    - filmphotography
    - ishootfilm
    - shootfilm
    - thefilmcommunity
  fujifilm:
    - fuji
    - fujifeed
    - fujifilm
    - fujifilm_xseries
    - fujifilmx_us
    - fujifilmxseries
    - fujilove
    - fujixclub
    - fujixseries
    - myfujifilm
  grandtetonnationalpark:
    - americasbestidea
    - encuentratuparque
    - findyourpark
    - goparks
    - grandtetonnationalpark
    - jacksonhole
    - mygrandteton
    - optoutside
    - tetons
  landscapes: &landscapes
    - allnatureshots
    - earth_deluxe
    - earthvisuals
    - fantastic_earth
    - ic_landscapes
    - instanaturelover
    - landscape_captures
    - landscape_lovers
    - landscapehunter
    - landscapelovers
    - landscapephotography
    - landscapes
    - nature_brilliance
    - nature_prefection
    - nature_shooters
    - nature_wizards
    - naturediversity
    - ourplanetdaily
    - special_shots
    - welivetoexplore
  telephotolandscapes: *landscapes
  lasvegas:
    - lasvegasstrip
    - sincity
    - vegas
    - vegasbaby
  leica:
    - ðŸ”´
    - leica
    - leicacamera
    - leicam
    - leicaphoto
    - leicaphotography
  longexposure:
    - amazing_longexpo
    - fs_longexpo
    - ic_longexpo
    - longexpo
    - longexpohunter
    - longexposure
    - longexposure_shots
    - longexposureoftheday
    - longexposurephotography
    - splendid_xposure
  magazines:
    - aintbadmagazine
    - aperturefoundation
    - archivecollectivemag
    - burnmagazine
    - foammagazine
    - gupmagazine
    - ifyouleave
    - lensculture
    - myfeatureshoot
    - noicemag
    - oftheafternoon
    - opendoorsgallery
    - organicamag
    - paperjournalmag
    - phroommagazine
    - somewheremagazine
    - subjectivelyobjective
    - yetmagazine
    - yourshotphotographer
  mexico:
    - ig_mexico
    - igersmexico
    - mexico
    - mexico_maravilloso
    - mexigers
    - mextagram
    - vive_mexico
  mountains:
    - mountainlove
    - instamountain
    - ig_mountains
    - mountainlife
    - mountainaddict
    - mountaingram
    - igersmountain
  nationalairandspacemuseum:
    - airandspace
  nationalgalleryofart:
    - myngadc
  nationalmall:
    - americasbestidea
    - encuentratuparque
    - findyourpark
    - goparks
    - optoutside
  nationalparks:
    - americasbestidea
    - encuentratuparque
    - findyourpark
    - goparks
    - optoutside
  nationalportraitgallery:
    - mynpg
  newyorkcity: &nyc
    - icapture_nyc
    - ig_great_shots_nyc
    - ig_nycity
    - igersofnyc
    - instagramnyc
    - made_in_ny
    - newyork_ig
    - newyork_instagram
    - newyorkcity
    - newyorknewyork
    - ny
    - nycprimeshot
    - unlimitednewyork
    - what_i_saw_in_nyc
  manhattan: *nyc
  brooklyn: *nyc
  queens: *nyc
  bronx: *nyc
  philadelphia:
    - discoverphl
    - explore215
    - explorephilly
    - igers_philly
    - igersphilly
    - instadelphia
    - instaphilly
    - philadelphia
    - philly
    - phillygram
    - phillyigers
    - phillylove
    - phillyprimeshots
    - phl
    - visitphilly
    - whyilovephilly
  pittsburgh:
    - '412'
    - pgh
    - pghcreative
    - steelcitygrammers
  scotland:
    - ig_scotland
    - insta_scotland
    - instascotland
    - visitscotland
  streetphotography:
    - everybodystreet
    - ig_street
    - lensculture
    - lensculturestreets
    - magnumphotos
    - seemycity
    - spicollective
    - street_photo_club
    - streetart
    - streetlife
    - streetlife_award
    - streetmagazine
    - streetmagazines
    - streetphotographer
    - streetphotographers
    - streets_vision
    - streetshot
    - urbanandstreet
  tennessee:
    - instagramtennessee
    - tn
  venezuela:
    - elnacionalweb
    - igersvenezuela
    - instavenezuela
    - vzla
  wildlife:
    - animal_in_world
    - animales
    - animallovers
    - animalofinstagram
    - animalsaddict
    - animalsmood
    - animalsofinstagram
    - animalworld
    - anmlsworld
    - exclusive_animals
    - fantastic_earth
    - planet_of_animals
    - thecritterhaven
    - wildlife
    - wildlife_seekers
    - wildlifeonearth
    - wildlifephoto
    - wildlifephotography
    - wildlifeplanet
  wyoming:
    - visitwyoming
    - wyoming
    - wyomingphotographer
    - wyomingexplored
    - wyomingphotography
    - naturalwyoming
  yellowstonenationalpark:
    - americasbestidea
    - encuentratuparque
    - findyourpark
    - goparks
    - optoutside
    - yellowstone
    - yellowstonepledge
  yosemitenationalpark:
    - americasbestidea
    - encuentratuparque
    - findyourpark
    - goparks
    - optoutside
