instagram:
  fujifilm:
    - fujifeed
    - fujifilmx_us
    - fujilove
    - fujifilm_xseries
  blackandwhite:
    - bnw
    - bw
    - blackandwhitephotography
    - monochrome
    - bnw_society
    - bnw_captures
    - bnw_life
  streetphotography:
    - spicollective
    - ig_street
    - everybodystreet
    - streetphoto
  scotland:
    - visitscotland
    - instascotland
    - insta_scotland
    - ig_scotland
  districtofcolumbia:
    - igdc
    - washingtondaily
    - exploredc
    - igersdc
    - walkwithlocals
  cats:
    - catsofinstagram
  mexico:
    - mextagram
    - mexigers
    - ig_mexico
    - mexico_maravilloso
  ciudaddemexico:
    - cdmx
    - mexicodf
    - mexicocity
    - igerscdmx
  newyorkcity:
    - newyork_instagram
    - instagramnyc
    - nycprimeshot
    - ig_nycity
  landscape:
    - landscape_lovers
    - landscapephotography
  architecture:
    - archilovers
    - architecturelovers
    - architectureporn
  all:
    - myfeatureshoot
    - somewheremagazine
    - lensculture
