entry: &entry
  src: 1440
  srcset:
    - 640
    - 1136
    - 750
    - 1334
    - 1242
    - 2208
    - 1125
    - 2436
    - 2048
    - 1536
    - 2224
    - 1668
    - 2732
    - 2880
    - 3360
    - 2560
    - 2880
    - 1680
  sizes:
    - "(min-width: 1680px) 1680px"
    - 100vw
entry_list: &entry_list
  src: 355
  srcset:
    - 304
    - 362
    - 360
    - 428
    - 390
    - 711
    - 540
    - 789
    - 666
    - 496
    - 724
    - 540
    - 666
    - 704
    - 824
    - 624
    - 704
  sizes:
    - "(min-width: 1680px) 412px"
    - "(min-width: 1280px) calc(25vw - 8px)"
    - "(min-width: 400px) calc(100vw/3 - 8px)"
    - 50vw
entry_list_square:
  <<: *entry_list
  square: Yes
admin_entry:
  <<: *entry
  sizes:
    - "(min-width: 840px) 840px"
    - 100vw
admin_edit:
  src: 300
  srcset:
    - 300
    - 516
    - 600
    - 626
    - 900
    - 1056
    - 1412
  sizes:
    - "(min-width: 800px) 300px"
    - calc(100vw - 60px)
map:
  src: 300
  srcset:
    - 300
    - 600
    - 900
  sizes:
    - 300px
  square: Yes
  auto: 'format,compress'
