entry: &entry
  src: 1440
  srcset:
    - 640
    - 750
    - 1014
    - 1242
    - 2048
    - 1536
    - 1388
    - 1014
    - 876
    - 2732
    - 1962
    - 1356
    - 1278
    - 1280
    - 1440
    - 2560
    - 2880
    - 2304
    - 1920
    - 3840
  sizes:
    - "(min-width: 1920px) 1920px"
    - 100vw
entry_amp:
  <<: *entry
  auto: 'format,compress'
entry_list_item:
  src: 355
  srcset:
    - 308
    - 333
    - 363
    - 603
    - 336
    - 251
    - 672
    - 502
    - 758
    - 422
    - 844
    - 355
    - 710
    - 900
  sizes:
    - "(min-width: 1440px) 355px"
    - "(min-width: 600px) calc((100vw - 16px)/3)"
    - calc((100vw - 12px)/2)
  square: Yes
  auto: 'format,compress'
admin_entry:
  src: 560
  srcset:
    - 560
    - 670
    - 800
    - 1122
    - 1456
    - 1600
  sizes:
    - "(min-width: 840px) 800px"
    - calc(100vw - 40px)
admin_edit:
  src: 300
  srcset:
    - 300
    - 516
    - 600
    - 626
    - 900
    - 1056
    - 1412
  sizes:
    - "(min-width: 800px) 300px"
    - calc(100vw - 60px)
map:
  src: 300
  srcset:
    - 300
    - 600
    - 900
  sizes:
    - 300px
  square: Yes
  auto: 'format,compress'
