entry: &entry
  src: 1440
  srcset:
    - 640
    - 750
    - 1242
    - 1536
    - 2048
    - 2732
    - 1280
    - 1440
    - 2560
    - 2880
    - 1680
    - 3360
    - 2304
  sizes:
    - "(min-width: 1680px) 1680px"
    - 100vw
entry_list_item:
  src: 355
  srcset:
    - 308
    - 315
    - 355
    - 363
    - 379
    - 398
    - 502
    - 630
    - 673
    - 710
    - 415
    - 830
  sizes:
    - "(min-width: 1680px) 415px"
    - "(min-width: 1280px) calc((100vw - 20px)/4)"
    - "(min-width: 400px) calc((100vw - 16px)/3)"
    - calc((100vw - 12px)/2)
  square: Yes
admin_entry:
  src: 560
  srcset:
    - 560
    - 670
    - 800
    - 1122
    - 1456
    - 1600
  sizes:
    - "(min-width: 840px) 800px"
    - calc(100vw - 40px)
  quality: 90
admin_edit:
  src: 300
  srcset:
    - 300
    - 516
    - 600
    - 626
    - 900
    - 1056
    - 1412
  sizes:
    - "(min-width: 800px) 300px"
    - calc(100vw - 60px)
map:
  src: 300
  srcset:
    - 300
    - 600
    - 900
  sizes:
    - 300px
  square: Yes
  auto: 'format,compress'
