entry: &entry
  src: 1440
  srcset:
    - 640
    - 1136
    - 750
    - 1334
    - 1242
    - 2208
    - 1125
    - 2436
    - 2048
    - 1536
    - 2224
    - 1668
    - 2732
    - 2880
    - 3360
    - 2560
    - 2880
    - 1680
  sizes:
    - "(min-width: 1680px) 1680px"
    - 100vw
  quality: 90
entry_list: &entry_list
  src: 355
  srcset:
    - 304
    - 362
    - 360
    - 428
    - 390
    - 711
    - 540
    - 789
    - 666
    - 496
    - 724
    - 540
    - 666
    - 704
    - 824
    - 624
    - 704
    - 412
  sizes:
    - "(min-width: 1680px) 412px"
    - "(min-width: 1280px) calc(25vw - 8px)"
    - "(min-width: 400px) calc(100vw/3 - 8px)"
    - "calc(50vw - 8px)"
entry_list_square:
  <<: *entry_list
  square: Yes
admin_entry:
  src: 1152
  srcset:
    - 544
    - 654
    - 1098
    - 981
    - 1440
    - 1952
    - 960
    - 1920
    - 1152
    - 2304
    - 1344
    - 2688
  sizes:
    - "(min-width: 1472px) 1344px"
    - "(min-width: 1280px) 1152px"
    - "(min-width: 1088px) 960px"
    - "calc(100vw - 3rem)"
admin_edit:
  src: 940
  srcset:
    - 544
    - 654
    - 1098
    - 1440
    - 780
    - 1560
    - 940
    - 1880
    - 1100
    - 2200
  sizes:
    - "(min-width: 1472px) 1100px"
    - "(min-width: 1280px) 940px"
    - "(min-width: 1088px) 780px"
    - "(min-width: 769px) calc(((100vw - 4.5rem)/6) * 5)"
    - "calc(100vw - 3rem)"
admin_queue:
  src: 490
  srcset:
    - 224
    - 280
    - 477
    - 672
    - 440
    - 168
    - 336
    - 207
    - 414
    - 245
    - 490
  sizes:
    - "(min-width: 1472px) 245px"
    - "(min-width: 1280px) 207px"
    - "(min-width: 1088px) 168px"
    - "(min-width: 769px) calc(((100vw - 3rem)/4) - 1.5rem)"
    - "calc((100vw - 3rem)/2 - 1.5rem)"
  square: Yes
map:
  src: 300
  srcset:
    - 300
    - 600
    - 900
  sizes:
    - 300px
  square: Yes
  auto: 'format,compress'
